name: Cattle Demo
description: |
    Test description
version: 0.1-rancher1 
category: Toy apps 
maintainer: Giovanni Colapinto <giovanni.colapinto@gmail.com> 
license: Apache2 
projectURL: http://nowhere 
